const ADD_NOTE = "ADD_NOTE";
const UPDATE_NOTE = "UPDATE_NOTE";
const UPDATE_NOTE_UNCOMPLETED = "UPDATE_NOTE_UNCOMPLETED";
const UPDATE_NOTE_COMPLETED = "UPDATE_NOTE_COMPLETED";
const REMOVE_NOTE = "REMOVE_NOTE";

export {
  ADD_NOTE,
  UPDATE_NOTE_UNCOMPLETED,
  UPDATE_NOTE_COMPLETED,
  REMOVE_NOTE,
  UPDATE_NOTE,
};
