const ADD_NOTE = "ADD_NOTE";
const UPDATE_NOTE_UNCOMPLETED = "UPDATE_NOTE_UNCOMPLETED";
const UPDATE_NOTE_COMPLETED = "UPDATE_NOTE_COMPLETED";

export { ADD_NOTE, UPDATE_NOTE_UNCOMPLETED, UPDATE_NOTE_COMPLETED };
